# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7f407fc54f756dc2171a837609638b8cce11094fb97c0b8f572dbb7e9cf73c9a4cbe5ba4dc20e6527a8501e3710b5ea34cb8a7e3ad9b5f42678126433f974a9

test:
  secret_key_base: af8673b9b9c1c48c28ba5b61d976011cd3381bb476c13d451e5fdacac2c2b9eaa30feb9519e13d9aa9863f000456ee21149a46f899adf95e0466e882193db2cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
